In [17]:
import numpy as np

In [73]:
l = np.array([1,2,3,4,5,6])
m = np.array([l for _ in range(len(l))])
m

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [74]:
age = np.array([-0.24, -1.38, 0.62, -0.9, 1.09, 0.81])
height = np.array([-0.7, -1.45, 0.35, 1.49, 0.06, 0.25])
weight = np.array([-0.68, -1.35, 0.68, 1.5, -0.08, -0.08])
bmi = np.array([-0.55, -1.31, 1.15, 1.23, -0.14, -0.38])



m_ahwb = np.array([age,height,weight,bmi]).T
m_ahwb

array([[-0.24, -0.7 , -0.68, -0.55],
       [-1.38, -1.45, -1.35, -1.31],
       [ 0.62,  0.35,  0.68,  1.15],
       [-0.9 ,  1.49,  1.5 ,  1.23],
       [ 1.09,  0.06, -0.08, -0.14],
       [ 0.81,  0.25, -0.08, -0.38]])

In [75]:
m_odl = np.zeros([max(m_ahwb.shape) for _ in range(2)])
m_odl

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [76]:
for k in range(m_odl.shape[0]):
    for w in range(m_odl.shape[0]):
        m_odl[w,k] = np.sqrt(sum((m_ahwb[k] - m_ahwb[w])**2))
print(m_odl)

[[0.         1.69958819 2.56548241 3.62663756 1.69546454 1.54722332]
 [1.69958819 0.         4.17282878 4.84232382 3.37087526 3.1880872 ]
 [2.56548241 4.17282878 0.         2.07094181 1.59583834 1.72180138]
 [3.62663756 4.84232382 2.07094181 0.         3.2215369  3.09033979]
 [1.69546454 3.37087526 1.59583834 3.2215369  0.         0.41484937]
 [1.54722332 3.1880872  1.72180138 3.09033979 0.41484937 0.        ]]


In [2]:
import pandas as pd

In [3]:
descriptors = pd.read_excel('Descriptors.xlsx')
descriptors.dropna()

Unnamed: 0  MaxAbsEStateIndex  MaxEStateIndex  MinAbsEStateIndex  \
0            0          12.034676       12.034676           0.546336   
1            1           9.471189        9.471189           0.501685   
2            2           5.469779        5.469779           0.639950   
3            3           8.539632        8.539632           0.491169   
4            4           6.112705        6.112705           0.382377   
5            5          10.368395       10.368395           0.085093   
6            6           8.394077        8.394077           0.475756   
7            7          10.465062       10.465062           0.008611   
8            8          12.455509       12.455509           0.401796   
9            9          10.091257       10.091257           0.087521   
10          10           6.091872        6.091872           0.094568   
11          11           5.971502        5.971502           0.208005   
12          12          10.319524       10.319524           0.282361   
13          13          11.802090       11.802090           0.122569   
14          14           6.183929        6.183929           0.375637   
15          15          10.533278       10.533278           0.044753   
16          16           5.537948        5.537948           0.269437   
17          17          10.508242       10.508242           0.242592   
18          18          10.180877       10.180877           0.010607   
19          19           5.174287        5.174287           1.011373   

    MinEStateIndex       qed        SPS    MolWt  HeavyAtomMolWt  ExactMolWt  \
0        -2.419051  0.588579  11.923077  242.346         223.194  242.056408   
1        -2.496043  0.550909  11.916667  246.359         231.239  245.997179   
2        -2.019869  0.374797  11.923077  260.386         243.250  260.012829   
3         0.491169  0.597687  17.750000  252.730         243.658  252.023645   
4        -1.456687  0.540334  11.894737  354.491         345.419  351.914689   
5        -1.182870  0.692552   9.636364  192.001         188.977  190.954084   
6         0.475756  0.333200  10.933333  222.679         211.591  222.067224   
7        -1.255370  0.686254   9.833333  207.016         202.984  205.964983   
8        -2.531319  0.566595  16.333333  270.400         247.216  270.087709   
9        -0.779282  0.355200  11.200000  249.683         241.619  249.008723   
10       -0.534860  0.615021  11.222222  320.046         309.966  317.953661   
11        0.208005  0.619326  10.222222  318.030         309.966  315.938011   
12       -0.707575  0.487998  17.235294  255.665         245.585  255.052302   
13       -2.648601  0.470197  12.842105  330.364         311.212  330.036067   
14       -1.455182  0.708530  11.523810  345.653         330.533  344.013763   
15       -1.309938  0.739877  10.076923  241.461         238.437  239.926010   
16       -2.076227  0.505229  13.133333  288.440         267.272  288.044130   
17       -0.718449  0.610588  18.444444  291.720         281.640  291.019288   
18       -1.130612  0.844246   9.928571  256.472         252.440  254.925676   
19       -1.984662  0.506070  11.916667  246.359         231.239  245.997179   

    ...  fr_sulfide  fr_sulfonamd  fr_sulfone  fr_term_acetylene  \
0   ...           0             0           0                  0   
1   ...           1             0           0                  0   
2   ...           1             0           0                  0   
3   ...           1             0           0                  0   
4   ...           0             0           0                  0   
5   ...           0             0           0                  0   
6   ...           0             0           0                  0   
7   ...           0             0           0                  0   
8   ...           0             0           0                  0   
9   ...           0             0           0                  0   
10  ...           0             0           0                 

In [12]:
for column in descriptors:
    if descriptors[column].var() == 0:
        descriptors = descriptors.drop(column, axis=1)

descriptors = descriptors.drop('Unnamed: 0', axis=1)

descriptors

MaxAbsEStateIndex  MaxEStateIndex  MinAbsEStateIndex  MinEStateIndex  \
0           12.034676       12.034676           0.546336       -2.419051   
1            9.471189        9.471189           0.501685       -2.496043   
2            5.469779        5.469779           0.639950       -2.019869   
3            8.539632        8.539632           0.491169        0.491169   
4            6.112705        6.112705           0.382377       -1.456687   
5           10.368395       10.368395           0.085093       -1.182870   
6            8.394077        8.394077           0.475756        0.475756   
7           10.465062       10.465062           0.008611       -1.255370   
8           12.455509       12.455509           0.401796       -2.531319   
9           10.091257       10.091257           0.087521       -0.779282   
10           6.091872        6.091872           0.094568       -0.534860   
11           5.971502        5.971502           0.208005        0.208005   
12          10.319524       10.319524           0.282361       -0.707575   
13          11.802090       11.802090           0.122569       -2.648601   
14           6.183929        6.183929           0.375637       -1.455182   
15          10.533278       10.533278           0.044753       -1.309938   
16           5.537948        5.537948           0.269437       -2.076227   
17          10.508242       10.508242           0.242592       -0.718449   
18          10.180877       10.180877           0.010607       -1.130612   
19           5.174287        5.174287           1.011373       -1.984662   

         qed        SPS    MolWt  HeavyAtomMolWt  ExactMolWt  \
0   0.588579  11.923077  242.346         223.194  242.056408   
1   0.550909  11.916667  246.359         231.239  245.997179   
2   0.374797  11.923077  260.386         243.250  260.012829   
3   0.597687  17.750000  252.730         243.658  252.023645   
4   0.540334  11.894737  354.491         345.419  351.914689   
5   0.692552   9.636364  192.001         188.977  190.954084   
6   0.333200  10.933333  222.679         211.591  222.067224   
7   0.686254   9.833333  207.016         202.984  205.964983   
8   0.566595  16.333333  270.400         247.216  270.087709   
9   0.355200  11.200000  249.683         241.619  249.008723   
10  0.615021  11.222222  320.046         309.966  317.953661   
11  0.619326  10.222222  318.030         309.966  315.938011   
12  0.487998  17.235294  255.665         245.585  255.052302   
13  0.470197  12.842105  330.364         311.212  330.036067   
14  0.708530  11.523810  345.653         330.533  344.013763   
15  0.739877  10.076923  241.461         238.437  239.926010   
16  0.505229  13.133333  288.440         267.272  288.044130   
17  0.610588  18.444444  291.720         281.640  291.019288   
18  0.844246   9.928571  256.472         252.440  254.925676   
19  0.506070  11.916667  246.359         231.239  245.997179   

    NumValenceElectrons  ...  fr_guanido  fr_halogen  fr_hdrzone  fr_methoxy  \
0                    80  ...           0           0           0           0   
1                    74  ...           0           0           0           0   
2                    80  ...           0           0           0           0   
3                    82  ...           0           1           0           0   
4                   100  ...           0           5           0           0   
5                    58  ...           0           2           0           0   
6                    78  ...           0           1           0           0   
7                    64  ...           0           2           0           0   
8                    92  ...           0           0           0           0   
9                    82  ...           1           1           1           0   
10                   94  ...           0           4           0           0   
11                   92  ...           0           4           0           0   
12                   9

In [15]:
for column in descriptors:
    for index, value in enumerate(descriptors[column]):
        descriptors[column][index] = (value - descriptors[column].mean())/descriptors[column].std()

descriptors

MaxAbsEStateIndex  MaxEStateIndex  MinAbsEStateIndex  MinEStateIndex  \
0           -0.184969       -0.184969           1.398106       -0.614905   
1           -0.896857       -0.896857           0.668299       -0.863965   
2           -1.718986       -1.718986           1.529124       -0.483525   
3           -0.827514       -0.827514           0.247770        2.564768   
4           -1.125005       -1.125005          -0.322669        0.067174   
5           -0.331702       -0.331702          -1.827935        0.255739   
6           -0.522243       -0.522243           0.356345        1.732773   
7           -0.142724       -0.142724          -1.395728        0.084829   
8            0.240303        0.240303           0.194941       -1.035026   
9            0.071880        0.071880          -0.766486        0.366566   
10          -0.407197       -0.407197          -0.617017        0.527584   
11          -0.355526       -0.355526          -0.202471        1.109092   
12           0.331966        0.331966           0.049516        0.281890   
13           0.724482        0.724482          -0.374532       -1.325581   
14           0.054973        0.054973           0.379508       -0.476269   
15           0.929567        0.929567          -0.533721       -0.406662   
16           0.253333        0.253333           0.139513       -1.162876   
17           1.484318        1.484318           0.080949        0.032146   
18           2.318226        2.318226          -0.525377       -0.403050   
19           2.080442        2.080442           2.159068       -1.286689   

         qed       SPS     MolWt  HeavyAtomMolWt  ExactMolWt  \
0  -0.887422 -1.423449 -1.585712       -1.677152   -1.581377   
1  -1.027252 -1.102997 -1.125970       -1.142341   -1.122979   
2  -2.612207 -0.915337 -0.836745       -0.864281   -0.833532   
3   0.125106 -0.009358 -0.760036       -0.738317   -0.759268   
4  -0.072038 -0.625689 -0.123256       -0.091801   -0.129007   
5   0.719906 -0.788139 -0.828375       -0.788515   -0.831023   
6  -0.948613 -0.553165 -0.600705       -0.597341   -0.600436   
7   0.708289 -0.579238 -0.590249       -0.559760   -0.592051   
8   0.227550  0.112384 -0.265425       -0.307296   -0.262909   
9  -0.563524 -0.252567 -0.269482       -0.257289   -0.268514   
10  0.541754 -0.173481  0.068695        0.080331    0.065795   
11  0.569048 -0.189533  0.168666        0.188963    0.165236   
12  0.084268  0.531308  0.041399        0.048242    0.042145   
13  0.070789  0.314324  0.433291        0.412720    0.436633   
14  1.019007  0.310628  0.686333        0.676918    0.685561   
15  1.050462  0.273890  0.453401        0.485764    0.450147   
16  0.143396  0.750273  0.872497        0.822409    0.875316   
17  0.561150  1.743915  1.259440        1.247200    1.262362   
18  1.393892  1.473442  1.663077        1.691404    1.660188   
19  0.101246  2.799423  2.803299        2.778789    2.805463   

    NumValenceElectrons  ...  fr_guanido  fr_halogen  fr_hdrzone  fr_methoxy  \
0             -1.385272  ...   -0.823811   -1.325876   -0.823811   -0.374889   
1             -1.229992  ...   -0.661611   -1.227302   -0.661611   -0.337511   
2             -0.886173  ...   -0.549240   -1.146842   -0.549240   -0.305275   
3             -0.721300  ...   -0.464367   -0.619581   -0.464367   -0.277130   
4             -0.322800  ...   -0.397081    1.214581   -0.397081   -0.252330   
5             -0.875829  ...   -0.342090    0.029301   -0.342090   -0.230321   
6             -0.507221  ...   -0.296226   -0.435760   -0.296226   -0.210678   
7             -0.614837  ...   -0.257428    0.125626   -0.257428   -0.193069   
8             -0.196782  ...   -0.224274   -0.852598   -0.224274   -0.177225   
9             -0.236501  ...    3.190027   -0.305352    3.190027   -0.162924   
10            -0.020089  ...   -0.298392    1.231973   -0.298392   -0.149983   
11             0.048708  ...   -0.272891    1.523799   -0.272891   -0.138245   
12             0.12216

In [20]:
descriptors_odl = np.zeros([descriptors.shape[0] for _ in range(2)])

for w in range(descriptors.shape[0]):
    for k in range(descriptors.shape[0]):
        descriptors_odl[w,k] = np.sqrt(sum((descriptors[descriptors.columns[w]] - descriptors[descriptors.columns[k]])**2))

print(descriptors_odl)

[[0.         0.         6.02227946 7.34749666 3.81631174 2.44799711
  2.70330967 2.72866415 2.70041779 2.49795851 4.46808491 7.23723812
  4.69627525 4.24571251 3.82033864 3.35451305 3.08549139 2.7361711
  2.02532505 2.62667926]
 [0.         0.         6.02227946 7.34749666 3.81631174 2.44799711
  2.70330967 2.72866415 2.70041779 2.49795851 4.46808491 7.23723812
  4.69627525 4.24571251 3.82033864 3.35451305 3.08549139 2.7361711
  2.02532505 2.62667926]
 [6.02227946 6.02227946 0.         6.74687234 7.15510336 5.40206283
  5.59086447 5.6746544  5.58438396 5.5046129  5.96735309 5.06018746
  6.74453281 5.89309634 6.52978519 6.41663019 6.37721136 5.95230284
  5.35006682 6.0832444 ]
 [7.34749666 7.34749666 6.74687234 0.         5.88541081 7.01991327
  7.29952961 7.26102206 7.3017271  7.30670839 6.68267303 5.78809049
  6.01579736 6.65708089 5.8624476  6.07406239 6.19722035 7.06363325
  7.31446736 6.95583354]
 [3.81631174 3.81631174 7.15510336 5.88541081 0.         4.38178579
  4.28332287 4.233