In [1]:
import numpy as np

In [2]:
l = np.array([1,2,3,4,5,6])
m = np.array([l for _ in range(len(l))])
m

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [3]:
age = np.array([-0.24, -1.38, 0.62, -0.9, 1.09, 0.81])
height = np.array([-0.7, -1.45, 0.35, 1.49, 0.06, 0.25])
weight = np.array([-0.68, -1.35, 0.68, 1.5, -0.08, -0.08])
bmi = np.array([-0.55, -1.31, 1.15, 1.23, -0.14, -0.38])



m_ahwb = np.array([age,height,weight,bmi]).T
m_ahwb

array([[-0.24, -0.7 , -0.68, -0.55],
       [-1.38, -1.45, -1.35, -1.31],
       [ 0.62,  0.35,  0.68,  1.15],
       [-0.9 ,  1.49,  1.5 ,  1.23],
       [ 1.09,  0.06, -0.08, -0.14],
       [ 0.81,  0.25, -0.08, -0.38]])

In [4]:
m_odl = np.zeros([max(m_ahwb.shape) for _ in range(2)])
m_odl

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
for k in range(m_odl.shape[0]):
    for w in range(m_odl.shape[0]):
        m_odl[w,k] = np.sqrt(sum((m_ahwb[k] - m_ahwb[w])**2))
print(m_odl)

[[0.         1.69958819 2.56548241 3.62663756 1.69546454 1.54722332]
 [1.69958819 0.         4.17282878 4.84232382 3.37087526 3.1880872 ]
 [2.56548241 4.17282878 0.         2.07094181 1.59583834 1.72180138]
 [3.62663756 4.84232382 2.07094181 0.         3.2215369  3.09033979]
 [1.69546454 3.37087526 1.59583834 3.2215369  0.         0.41484937]
 [1.54722332 3.1880872  1.72180138 3.09033979 0.41484937 0.        ]]


In [6]:
import pandas as pd

In [7]:
descriptors = pd.read_excel('Descriptors.xlsx')
descriptors.dropna()

Unnamed: 0  MaxAbsEStateIndex  MaxEStateIndex  MinAbsEStateIndex  \
0            0          12.034676       12.034676           0.546336   
1            1           5.507495        5.507495           0.644046   
2            2           5.469779        5.469779           0.639950   
3            3           8.539632        8.539632           0.491169   
4            4           6.112705        6.112705           0.382377   
5            5          10.368395       10.368395           0.085093   
6            6           8.394077        8.394077           0.475756   
7            7          10.465062       10.465062           0.008611   
8            8          12.455509       12.455509           0.401796   
9            9          10.091257       10.091257           0.087521   
10          10           6.091872        6.091872           0.094568   
11          11           5.971502        5.971502           0.208005   
12          12          10.319524       10.319524           0.282361   
13          13          11.802090       11.802090           0.122569   
14          14           6.183929        6.183929           0.375637   
15          15          10.533278       10.533278           0.044753   
16          16           5.537948        5.537948           0.269437   
17          17          10.508242       10.508242           0.242592   
18          18          10.180877       10.180877           0.010607   
19          19           5.174287        5.174287           1.011373   

    MinEStateIndex       qed        SPS    MolWt  HeavyAtomMolWt  ExactMolWt  \
0        -2.419051  0.588579  11.923077  242.346         223.194  242.056408   
1        -2.022856  0.469026  11.928571  274.413         255.261  274.028479   
2        -2.019869  0.374797  11.923077  260.386         243.250  260.012829   
3         0.491169  0.597687  17.750000  252.730         243.658  252.023645   
4        -1.456687  0.540334  11.894737  354.491         345.419  351.914689   
5        -1.182870  0.692552   9.636364  192.001         188.977  190.954084   
6         0.475756  0.333200  10.933333  222.679         211.591  222.067224   
7        -1.255370  0.686254   9.833333  207.016         202.984  205.964983   
8        -2.531319  0.566595  16.333333  270.400         247.216  270.087709   
9        -0.779282  0.355200  11.200000  249.683         241.619  249.008723   
10       -0.534860  0.615021  11.222222  320.046         309.966  317.953661   
11        0.208005  0.619326  10.222222  318.030         309.966  315.938011   
12       -0.707575  0.487998  17.235294  255.665         245.585  255.052302   
13       -2.648601  0.470197  12.842105  330.364         311.212  330.036067   
14       -1.455182  0.708530  11.523810  345.653         330.533  344.013763   
15       -1.309938  0.739877  10.076923  241.461         238.437  239.926010   
16       -2.076227  0.505229  13.133333  288.440         267.272  288.044130   
17       -0.718449  0.610588  18.444444  291.720         281.640  291.019288   
18       -1.130612  0.844246   9.928571  256.472         252.440  254.925676   
19       -1.984662  0.506070  11.916667  246.359         231.239  245.997179   

    ...  fr_sulfide  fr_sulfonamd  fr_sulfone  fr_term_acetylene  \
0   ...           0             0           0                  0   
1   ...           1             0           0                  0   
2   ...           1             0           0                  0   
3   ...           1             0           0                  0   
4   ...           0             0           0                  0   
5   ...           0             0           0                  0   
6   ...           0             0           0                  0   
7   ...           0             0           0                  0   
8   ...           0             0           0                  0   
9   ...           0             0           0                  0   
10  ...           0             0           0                 

In [8]:
for column in descriptors:
    if descriptors[column].var() == 0:
        descriptors = descriptors.drop(column, axis=1)

descriptors = descriptors.drop('Unnamed: 0', axis=1)

descriptors

MaxAbsEStateIndex  MaxEStateIndex  MinAbsEStateIndex  MinEStateIndex  \
0           12.034676       12.034676           0.546336       -2.419051   
1            5.507495        5.507495           0.644046       -2.022856   
2            5.469779        5.469779           0.639950       -2.019869   
3            8.539632        8.539632           0.491169        0.491169   
4            6.112705        6.112705           0.382377       -1.456687   
5           10.368395       10.368395           0.085093       -1.182870   
6            8.394077        8.394077           0.475756        0.475756   
7           10.465062       10.465062           0.008611       -1.255370   
8           12.455509       12.455509           0.401796       -2.531319   
9           10.091257       10.091257           0.087521       -0.779282   
10           6.091872        6.091872           0.094568       -0.534860   
11           5.971502        5.971502           0.208005        0.208005   
12          10.319524       10.319524           0.282361       -0.707575   
13          11.802090       11.802090           0.122569       -2.648601   
14           6.183929        6.183929           0.375637       -1.455182   
15          10.533278       10.533278           0.044753       -1.309938   
16           5.537948        5.537948           0.269437       -2.076227   
17          10.508242       10.508242           0.242592       -0.718449   
18          10.180877       10.180877           0.010607       -1.130612   
19           5.174287        5.174287           1.011373       -1.984662   

         qed        SPS    MolWt  HeavyAtomMolWt  ExactMolWt  \
0   0.588579  11.923077  242.346         223.194  242.056408   
1   0.469026  11.928571  274.413         255.261  274.028479   
2   0.374797  11.923077  260.386         243.250  260.012829   
3   0.597687  17.750000  252.730         243.658  252.023645   
4   0.540334  11.894737  354.491         345.419  351.914689   
5   0.692552   9.636364  192.001         188.977  190.954084   
6   0.333200  10.933333  222.679         211.591  222.067224   
7   0.686254   9.833333  207.016         202.984  205.964983   
8   0.566595  16.333333  270.400         247.216  270.087709   
9   0.355200  11.200000  249.683         241.619  249.008723   
10  0.615021  11.222222  320.046         309.966  317.953661   
11  0.619326  10.222222  318.030         309.966  315.938011   
12  0.487998  17.235294  255.665         245.585  255.052302   
13  0.470197  12.842105  330.364         311.212  330.036067   
14  0.708530  11.523810  345.653         330.533  344.013763   
15  0.739877  10.076923  241.461         238.437  239.926010   
16  0.505229  13.133333  288.440         267.272  288.044130   
17  0.610588  18.444444  291.720         281.640  291.019288   
18  0.844246   9.928571  256.472         252.440  254.925676   
19  0.506070  11.916667  246.359         231.239  245.997179   

    NumValenceElectrons  ...  fr_guanido  fr_halogen  fr_hdrzone  fr_methoxy  \
0                    80  ...           0           0           0           0   
1                    86  ...           0           0           0           0   
2                    80  ...           0           0           0           0   
3                    82  ...           0           1           0           0   
4                   100  ...           0           5           0           0   
5                    58  ...           0           2           0           0   
6                    78  ...           0           1           0           0   
7                    64  ...           0           2           0           0   
8                    92  ...           0           0           0           0   
9                    82  ...           1           1           1           0   
10                   94  ...           0           4           0           0   
11                   92  ...           0           4           0           0   
12                   9

In [9]:
for column in descriptors:
    for index, value in enumerate(descriptors[column]):
        descriptors[column][index] = (value - descriptors[column].mean())/descriptors[column].std()

descriptors

/tmp/ipykernel_642/268904455.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  descriptors[column][index] = (value - descriptors[column].mean())/descriptors[column].std()
/tmp/ipykernel_642/268904455.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  descriptors[column][index] = (value - descriptors[column].mean())/descriptors[column].std()
/tmp/ipykernel_642/268904455.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  descriptors[

MaxAbsEStateIndex  MaxEStateIndex  MinAbsEStateIndex  MinEStateIndex  \
0            1.347782        1.347782           0.862653       -1.235383   
1           -0.879493       -0.879493           1.081422       -0.917970   
2           -0.650045       -0.650045           0.870242       -0.997709   
3            0.282894        0.282894           0.357990        1.837772   
4           -0.213173       -0.213173           0.055369       -0.425656   
5            0.810581        0.810581          -0.764773       -0.208407   
6            0.470149        0.470149           0.405781        1.340703   
7            0.974016        0.974016          -0.697526       -0.339119   
8            1.495738        1.495738           0.287363       -1.519006   
9            1.171780        1.171780          -0.366959        0.000779   
10           0.394291        0.394291          -0.291785        0.191999   
11           0.425317        0.425317          -0.020546        0.834597   
12           1.444910        1.444910           0.148889       -0.030226   
13           1.979036        1.979036          -0.153385       -1.764463   
14           0.878566        0.878566           0.369187       -0.802298   
15           2.131496        2.131496          -0.275973       -0.708990   
16           1.044177        1.044177           0.190346       -1.484224   
17           2.734071        2.734071           0.146622       -0.215072   
18           3.573905        3.573905          -0.289271       -0.651366   
19           2.785406        2.785406           1.632419       -1.544140   

         qed       SPS     MolWt  HeavyAtomMolWt  ExactMolWt  \
0   0.173317 -0.209270 -0.643254       -0.835801   -0.632613   
1  -0.476901  0.010170  0.206397        0.102491    0.214949   
2  -0.440694  0.132597  0.160669        0.089551    0.167314   
3   0.404691  1.313555  0.188277        0.197361    0.191007   
4   0.268844  0.367031  1.117280        1.161508    1.108040   
5   0.743673  0.056615 -0.078321       -0.038162   -0.080992   
6  -0.293464  0.339428  0.227711        0.214778    0.229203   
7   0.728642  0.237726  0.184836        0.219488    0.182773   
8   0.411602  1.271554  0.684216        0.601508    0.688844   
9  -0.113643  0.633030  0.622775        0.635821    0.624690   
10  0.594011  0.709177  1.163217        1.182845    1.157650   
11  0.608251  0.634950  1.278335        1.314744    1.271844   
12  0.283456  1.757304  0.993564        1.002195    0.994825   
13  0.264911  1.324416  1.625786        1.593324    1.630896   
14  0.884552  1.257485  1.980812        1.975058    1.978035   
15  0.917861  1.143222  1.482274        1.542760    1.476048   
16  0.317691  1.828218  2.101990        2.029027    2.105512   
17  0.591251  3.223357  2.589637        2.594832    2.592226   
18  1.150622  2.505866  2.988769        3.063474    2.981456   
19  0.292718  3.998323  4.247907        4.247776    4.247908   

    NumValenceElectrons  ...  fr_guanido  fr_halogen  fr_hdrzone  fr_methoxy  \
0             -0.395315  ...   -0.409447   -0.965678   -0.409447   -0.223607   
1              0.184923  ...   -0.335494   -0.900588   -0.335494   -0.196240   
2              0.090375  ...   -0.282536   -0.846194   -0.282536   -0.172981   
3              0.251741  ...   -0.241629   -0.234258   -0.241629   -0.152972   
4              0.807222  ...   -0.208658    2.020390   -0.208658   -0.135607   
5             -0.154936  ...   -0.181368    0.497803   -0.181368   -0.120435   
6              0.389148  ...   -0.158372   -0.080582   -0.158372   -0.107112   
7              0.146340  ...   -0.138751    0.571875   -0.138751   -0.095369   
8              0.812291  ...   -0.121859   -0.624322   -0.121859   -0.084986   
9              0.686702  ...    2.218879    0.017193    2.218879   -0.075785   
10             1.015960  ...   -0.173300    1.868417   -0.173300   -0.067616   
11             1.081452  ...   -0.158554    2.122900   -0.158554   -0.060353   
12             1.15502

In [10]:
descriptors_odl = np.zeros([descriptors.shape[0] for _ in range(2)])

for w in range(descriptors.shape[0]):
    for k in range(descriptors.shape[0]):
        descriptors_odl[w,k] = np.sqrt(sum((descriptors[descriptors.columns[w]] - descriptors[descriptors.columns[k]])**2))

print(descriptors_odl)

[[ 0.          0.          7.22541092 10.11030988  5.32415739  3.45702167
   4.11294788  4.16090617  4.10722567  3.83835249  5.92007807  8.50352004
   5.98554597  5.90766567  4.62906068  4.10259691  3.81164213  3.82324814
   3.07567739  3.41565193]
 [ 0.          0.          7.22541092 10.11030988  5.32415739  3.45702167
   4.11294788  4.16090617  4.10722567  3.83835249  5.92007807  8.50352004
   5.98554597  5.90766567  4.62906068  4.10259691  3.81164213  3.82324814
   3.07567739  3.41565193]
 [ 7.22541092  7.22541092  0.          6.10978584  4.0857949   6.47597327
   6.90599478  7.02069999  6.89569226  6.88228671  3.35127816  3.33428146
   3.61561149  3.3422842   4.69528889  5.12504737  5.42513505  7.02645357
   6.29172615  5.12576406]
 [10.11030988 10.11030988  6.10978584  0.          5.82431735  9.89377711
  10.42039089 10.39344101 10.41997725 10.4856192   5.71527372  4.50529512
   5.59155474  5.70246241  6.48333522  7.10546959  7.46896421 10.03738803
  10.10045217  8.48005161]
 [ 5